String userIdKey = "USERIDKEY";
String nameKey = "NAMEKEY";
String emailKey = "EMAILKEY";
String walletKey = "WALLETKEY";
String userProfile = "USERPROFILE";
String paymobApiKey =
    "ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2TVRBek5EQTNPQ3dpYm1GdFpTSTZJbWx1YVhScFlXd2lmUS5Za1VobFNBczN3bVRJXzJueGExOW5lVUMzeE1TVy0wbTVIUmhSWGRoNG1pUlNpVm9TVUJvdGJKVjVBMG52RnVrUXFINkZob0R3VHdUcjZwY19uRWFidw==";
